version: '3.4'

services:
    hsc.samplewebapi:
        image: ${DOCKER_REGISTRY-}hscsamplewebapi
        build:
          context: .
          dockerfile: Hsc.SampleWebApi/Dockerfile
        ports:
          - "5003:443"
          - "5002:80"
        environment:
            #change this to the actual URL in production environments
            HSC_JWT_AUDIENCE: "https://localhost:5003"
            #change this to the actual URL  in production environments
            HSC_JWT_ISSUER:  "https://localhost:5003"
            #for example purposes only - change this to a different secret
            HSC_JWT_SECRET: "qxBCtzLpUZRaBppKLQrnopqco88KNYEyVxF6F1W9"
            #for example purposes only - don't use sa user or this default password in a production environment'
            HSC_DATABASE_CONNECTION: Server=db01;Initial Catalog=ApiDb;User=sa;Password=FzyNPObxGgBT69DlD4ncHJtovNIMG2;

        depends_on:
          - db01
    db01:
        image: mcr.microsoft.com/mssql/server
        container_name: Hsc.SampleWebApi.Database
        volumes:
          - mssqldata:/var/opt/mssql
        environment:
            SA_PASSWORD: "FzyNPObxGgBT69DlD4ncHJtovNIMG2"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"